CREATE DATABASE VeiculosAntigosDb;
USE VeiculosAntigosDb;

CREATE TABLE Fabricante (
	Id UNIQUEIDENTIFIER NOT NULL,
	NomeFabricante VARCHAR(200) NOT NULL,
	CONSTRAINT PK_Fabricante PRIMARY KEY (Id)
)
GO

CREATE TABLE TipoDeVeiculo (
	Id UNIQUEIDENTIFIER  NOT NULL,
	Tipo VARCHAR(100),
	CONSTRAINT PK_TipoDeVeiculo PRIMARY KEY (Id)
)

--DROP TABLE Veiculo
CREATE TABLE Veiculo (
	Id UNIQUEIDENTIFIER NOT NULL,
	Descricao VARCHAR(500) NOT NULL,
	Ano INT NOT NULL,
	IdFabricante UNIQUEIDENTIFIER NOT NULL,
	IdTipo UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT PK_Veiculo PRIMARY KEY (Id),
	CONSTRAINT FK_Veiculo_Fabricante FOREIGN KEY (IdFabricante) REFERENCES Fabricante(Id),
	CONSTRAINT FK_Veiculo_Tipo FOREIGN KEY (IdTipo) REFERENCES TipoDeVeiculo(Id),
)
